// popup.js — Cookie Extractor Extension

let allCookies = [];
let currentDomain = "";
let currentUrl = "";

// ── Formatters ────────────────────────────────────────────────────────────────

function toNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by Cookie Extractor extension",
    "# https://curl.se/docs/http-cookies.html",
    "",
  ];
  cookies.forEach((c) => {
    const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
    const subdomains = c.domain.startsWith(".") ? "TRUE" : "FALSE";
    const secure = c.secure ? "TRUE" : "FALSE";
    const exp = c.expires ? Math.round(c.expires) : 0;
    lines.push([domain, subdomains, c.path, secure, exp, c.name, c.value].join("\t"));
  });
  return lines.join("\n");
}

function toHeader(cookies) {
  return "Cookie: " + cookies.map((c) => `${c.name}=${c.value}`).join("; ");
}

function toPlaywright(cookies) {
  const sameSiteMap = { no_restriction: "None", lax: "Lax", strict: "Strict" };
  const pw = cookies.map((c) => ({
    name:     c.name,
    value:    c.value,
    domain:   c.domain.startsWith(".") ? c.domain.slice(1) : c.domain,
    path:     c.path,
    secure:   c.secure,
    httpOnly: c.httpOnly,
    sameSite: sameSiteMap[c.sameSite] || "None",
    ...(c.expires ? { expires: c.expires } : {}),
  }));
  return JSON.stringify({ cookies: pw, origins: [] }, null, 2);
}

function toPuppeteer(cookies) {
  return JSON.stringify(
    cookies.map((c) => ({
      name:     c.name,
      value:    c.value,
      domain:   c.domain,
      path:     c.path,
      expires:  c.expires || -1,
      secure:   c.secure,
      httpOnly: c.httpOnly,
      sameSite: c.sameSite === "no_restriction" ? "None"
               : c.sameSite === "lax"           ? "Lax"
               : c.sameSite === "strict"         ? "Strict"
               : "None",
      session:  c.session,
    })),
    null,
    2
  );
}

// ── Utilities ─────────────────────────────────────────────────────────────────

function copyText(text) {
  navigator.clipboard.writeText(text).catch(() => {
    // fallback for older MV3 implementations
    const ta = document.createElement("textarea");
    ta.value = text;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand("copy");
    document.body.removeChild(ta);
  });
}

function showToast(msg) {
  const t = document.getElementById("toast");
  t.textContent = msg;
  t.classList.add("show");
  clearTimeout(t._tid);
  t._tid = setTimeout(() => t.classList.remove("show"), 1800);
}

function downloadFile(filename, content, mime) {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function safeName(domain) {
  return domain.replace(/[^a-z0-9.-]/gi, "_");
}

// ── Render cookie list ────────────────────────────────────────────────────────

function renderCookies(filter = "") {
  const list = document.getElementById("cookie-list");
  const lower = filter.toLowerCase();
  const filtered = allCookies.filter(
    (c) =>
      !lower ||
      c.name.toLowerCase().includes(lower) ||
      c.value.toLowerCase().includes(lower)
  );

  document.getElementById("count-badge").textContent =
    `${filtered.length} cookie${filtered.length !== 1 ? "s" : ""}`;

  if (!filtered.length) {
    list.innerHTML = `
      <div class="empty-state">
        <div class="empty-icon">🔍</div>
        <div class="empty-title">No cookies found</div>
        <div class="empty-sub">${
          allCookies.length
            ? "Try a different search term"
            : "No cookies set for this domain"
        }</div>
      </div>`;
    return;
  }

  list.innerHTML = filtered
    .map((c) => {
      const flags = [
        c.secure   ? `<span class="flag flag-secure">Secure</span>`   : "",
        c.httpOnly ? `<span class="flag flag-httponly">HttpOnly</span>` : "",
        c.session  ? `<span class="flag flag-session">Session</span>`  : "",
      ]
        .filter(Boolean)
        .join("");

      const preview = c.value.length > 55
        ? c.value.slice(0, 55) + "…"
        : c.value;

      const expStr = c.session
        ? "Session"
        : c.expires
        ? new Date(c.expires * 1000).toLocaleString()
        : "—";

      return `
        <div class="cookie-item" data-name="${escHtml(c.name)}" title="Click to copy value">
          <div class="cookie-row">
            <span class="cookie-name">${escHtml(c.name)}</span>
            <span class="cookie-value">${escHtml(preview)}</span>
            <div class="cookie-flags">${flags}</div>
          </div>
          <div class="cookie-meta">
            ${escHtml(c.domain)}${c.path !== "/" ? escHtml(c.path) : ""}
            &nbsp;·&nbsp;${c.sameSite}
            &nbsp;·&nbsp;${expStr}
          </div>
        </div>`;
    })
    .join("");

  // Click to copy value
  list.querySelectorAll(".cookie-item").forEach((el) => {
    el.addEventListener("click", () => {
      const name = el.dataset.name;
      const cookie = allCookies.find((c) => c.name === name);
      if (cookie) {
        copyText(cookie.value);
        showToast(`Copied: ${name}`);
      }
    });
  });
}

// ── Render export panel ───────────────────────────────────────────────────────

function renderExport() {
  if (!allCookies.length) {
    document.getElementById("export-panel").innerHTML = `
      <div class="empty-state">
        <div class="empty-icon">📭</div>
        <div class="empty-title">No cookies to export</div>
        <div class="empty-sub">Navigate to a page and refresh</div>
      </div>`;
    return;
  }

  const dn = safeName(currentDomain);
  const formats = [
    {
      id:    "json",
      label: "JSON",
      desc:  "Full structured data — all fields",
      ext:   ".json",
      mime:  "application/json",
      fn:    () => JSON.stringify(allCookies, null, 2),
    },
    {
      id:    "netscape",
      label: "Netscape / curl",
      desc:  "curl -b · wget --load-cookies",
      ext:   ".txt",
      mime:  "text/plain",
      fn:    () => toNetscape(allCookies),
    },
    {
      id:    "header",
      label: "HTTP Header",
      desc:  "Cookie: header string — Postman, curl -H",
      ext:   ".hdr",
      mime:  "text/plain",
      fn:    () => toHeader(allCookies),
    },
    {
      id:    "playwright",
      label: "Playwright storageState",
      desc:  "browser.new_context(storage_state=…)",
      ext:   ".playwright.json",
      mime:  "application/json",
      fn:    () => toPlaywright(allCookies),
    },
    {
      id:    "puppeteer",
      label: "Puppeteer / CDP",
      desc:  "page.setCookie(…cookies)",
      ext:   ".puppeteer.json",
      mime:  "application/json",
      fn:    () => toPuppeteer(allCookies),
    },
  ];

  document.getElementById("export-panel").innerHTML = formats
    .map((f) => {
      const preview = f.fn().slice(0, 300);
      return `
        <div class="format-block">
          <div class="format-header">
            <div>
              <span class="format-label">${f.label}</span>
              <span class="format-desc">${f.desc}</span>
            </div>
            <div class="format-actions">
              <button class="btn btn-ghost" data-action="copy" data-id="${f.id}">Copy</button>
              <button class="btn btn-primary" data-action="download" data-id="${f.id}" data-ext="${f.ext}" data-mime="${f.mime}">⬇ Save</button>
            </div>
          </div>
          <div class="code-block" id="preview-${f.id}">${escHtml(preview)}${f.fn().length > 300 ? "…" : ""}</div>
        </div>`;
    })
    .join("");

  // Wire up buttons
  document.getElementById("export-panel").querySelectorAll("[data-action]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const fmt = formats.find((f) => f.id === btn.dataset.id);
      const content = fmt.fn();
      if (btn.dataset.action === "copy") {
        copyText(content);
        showToast(`Copied ${fmt.label}`);
      } else {
        downloadFile(`cookies_${dn}${btn.dataset.ext}`, content, btn.dataset.mime);
        showToast(`Saved cookies_${dn}${btn.dataset.ext}`);
      }
    });
  });
}

// ── Render raw JSON ───────────────────────────────────────────────────────────

function renderRaw() {
  const json = JSON.stringify(allCookies, null, 2);
  document.getElementById("raw-code").textContent = json;
}

// ── Load cookies ──────────────────────────────────────────────────────────────

function loadCookies() {
  document.getElementById("cookie-list").innerHTML = `
    <div class="empty-state">
      <div class="empty-icon">⏳</div>
      <div class="empty-title">Loading…</div>
    </div>`;

  chrome.tabs.query({ active: true, currentWindow: true }, ([tab]) => {
    if (!tab || !tab.url) return;
    currentUrl = tab.url;

    try {
      const urlObj = new URL(tab.url);
      currentDomain = urlObj.hostname;
    } catch {
      currentDomain = tab.url;
    }

    document.getElementById("domain-badge").textContent = currentDomain;

    chrome.runtime.sendMessage(
      { action: "getCookies", url: currentUrl, domain: currentDomain },
      (response) => {
        if (chrome.runtime.lastError || !response) {
          document.getElementById("cookie-list").innerHTML = `
            <div class="empty-state">
              <div class="empty-icon">⚠️</div>
              <div class="empty-title">Could not fetch cookies</div>
              <div class="empty-sub">${chrome.runtime.lastError?.message || "Unknown error"}</div>
            </div>`;
          return;
        }

        allCookies = response.cookies;
        renderCookies(document.getElementById("search").value);
        renderExport();
        renderRaw();
      }
    );
  });
}

// ── Tab switching ─────────────────────────────────────────────────────────────

function escHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

document.querySelectorAll(".tab").forEach((tab) => {
  tab.addEventListener("click", () => {
    document.querySelectorAll(".tab").forEach((t) => t.classList.remove("active"));
    document.querySelectorAll(".panel").forEach((p) => p.classList.remove("active"));
    tab.classList.add("active");
    document.getElementById(`panel-${tab.dataset.tab}`).classList.add("active");
  });
});

// ── Search ────────────────────────────────────────────────────────────────────

document.getElementById("search").addEventListener("input", (e) => {
  renderCookies(e.target.value);
});

// ── Buttons ───────────────────────────────────────────────────────────────────

document.getElementById("btn-refresh").addEventListener("click", loadCookies);

document.getElementById("btn-copy-raw").addEventListener("click", () => {
  copyText(JSON.stringify(allCookies, null, 2));
  showToast("JSON copied");
});

document.getElementById("btn-download-json").addEventListener("click", () => {
  const dn = safeName(currentDomain);
  downloadFile(
    `cookies_${dn}.json`,
    JSON.stringify(allCookies, null, 2),
    "application/json"
  );
  showToast(`Saved cookies_${dn}.json`);
});

// ── Init ──────────────────────────────────────────────────────────────────────

loadCookies();
